import { useLocation } from 'react-router-dom'
import { Bell, Circle } from 'lucide-react'

const titles = {
  '/dashboard': { title: 'Operations Dashboard', sub: 'Today · May 25, 2026' },
  '/calls':     { title: 'Active Calls',          sub: 'ARIA is handling these calls in real time' },
  '/tickets':   { title: 'Tickets Queue',         sub: 'All tickets auto-generated by ARIA' },
  '/settings':  { title: 'Settings',              sub: 'System configuration & routing rules' },
}

function Topbar() {
  const { pathname } = useLocation()
  const base = '/' + pathname.split('/')[1]
  const { title, sub } = titles[base] || { title: 'ARIA', sub: '' }

  return (
    <div className="h-14 bg-white border-b border-slate-200 flex items-center justify-between px-6 flex-shrink-0">
      <div>
        <div className="text-sm font-bold text-slate-900 tracking-tight">{title}</div>
        {sub && <div className="text-[11px] text-slate-400 mt-0.5">{sub}</div>}
      </div>
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2 bg-emerald-50 border border-emerald-200 text-emerald-700 text-[11px] font-semibold px-3 py-1.5 rounded-md">
          <Circle size={6} fill="#10b981" color="#10b981" />
          System Online
        </div>
        <div className="w-8 h-8 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-center cursor-pointer hover:bg-slate-100 transition-all">
          <Bell size={14} color="#64748b" />
        </div>
      </div>
    </div>
  )
}

export default Topbar