import { useNavigate } from 'react-router-dom'
import useAriaStore from '../../store/ariaStore'
import { CATEGORIES } from '../../data/mockData'

const STATUS_STYLES = {
  'Open':        { bg: '#EFF6FF', text: '#1D4ED8', border: '#BFDBFE' },
  'In Progress': { bg: '#FFFBEB', text: '#B45309', border: '#FDE68A' },
  'Resolved':    { bg: '#F0FDF4', text: '#15803D', border: '#BBF7D0' },
}

const PRIORITY_STYLES = {
  'High':   { bg: '#FEF2F2', text: '#B91C1C', border: '#FECACA' },
  'Medium': { bg: '#FFFBEB', text: '#B45309', border: '#FDE68A' },
  'Low':    { bg: '#F0FDF4', text: '#15803D', border: '#BBF7D0' },
}

function Badge({ label, styles }) {
  const s = styles[label] || { bg: '#F1F5F9', text: '#475569', border: '#E2E8F0' }
  return (
    <span
      className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-semibold"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}
    >
      {label}
    </span>
  )
}

const HEADERS = ['Ticket ID', 'Customer', 'Category', 'Department', 'Priority', 'Status', 'Time']

function RecentTickets() {
  const tickets = useAriaStore((s) => s.tickets)
  const navigate = useNavigate()

  return (
    <div className="bg-white rounded-xl border border-slate-200">
      <div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between">
        <div>
          <div className="text-sm font-bold text-slate-900">Recent Tickets</div>
          <div className="text-[11px] text-slate-400 mt-0.5">Auto-generated by ARIA from call recordings</div>
        </div>
        <button
          onClick={() => navigate('/tickets')}
          className="text-xs font-semibold text-blue-600 border border-blue-200 bg-blue-50 px-3 py-1.5 rounded-md hover:bg-blue-100 transition-all"
        >
          View All →
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <thead>
            <tr>
              {HEADERS.map((h) => (
                <th
                  key={h}
                  className="px-4 py-3 text-left text-[10.5px] font-bold text-slate-400 uppercase tracking-wider border-b border-slate-100 bg-slate-50 whitespace-nowrap"
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {tickets.slice(0, 5).map((t, i) => {
              const cat = CATEGORIES[t.category]
              return (
                <tr
                  key={t.id}
                  onClick={() => navigate('/tickets')}
                  className="cursor-pointer hover:bg-blue-50 transition-colors"
                  style={{ background: i % 2 === 0 ? '#fff' : '#fafbfc' }}
                >
                  <td className="px-4 py-3 border-b border-slate-100">
                    <span className="font-mono text-xs font-bold text-blue-600">{t.id}</span>
                  </td>
                  <td className="px-4 py-3 border-b border-slate-100">
                    <div className="text-sm font-semibold text-slate-800">{t.customer}</div>
                    <div className="text-[11px] text-slate-400">{t.contact}</div>
                  </td>
                  <td className="px-4 py-3 border-b border-slate-100">
                    <span
                      className="text-[11px] font-semibold px-2 py-0.5 rounded-full"
                      style={{ background: cat.bg, color: cat.color, border: `1px solid ${cat.border}` }}
                    >
                      {cat.label}
                    </span>
                  </td>
                  <td className="px-4 py-3 border-b border-slate-100 text-xs text-slate-600">{t.dept}</td>
                  <td className="px-4 py-3 border-b border-slate-100">
                    <Badge label={t.priority} styles={PRIORITY_STYLES} />
                  </td>
                  <td className="px-4 py-3 border-b border-slate-100">
                    <Badge label={t.status} styles={STATUS_STYLES} />
                  </td>
                  <td className="px-4 py-3 border-b border-slate-100 text-[11px] text-slate-400 whitespace-nowrap">{t.time}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default RecentTickets